name: teenfit
description: Aplikasi kesehatan remaja wanita.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0
  firebase_auth: ^0.15.5
  firebase_database: ^3.1.1
  provider: ^4.0.4
  intl: 0.16.1
  flutter_swiper: any
  email_validator: '^1.0.4'
  flutter_local_notifications: ^1.3.0
  gradient_app_bar: ^0.0.1
  flutter_time_picker_spinner: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/teenfit-icon.png
    - assets/images/
    